In [8]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # data visualisation
import matplotlib.pyplot as plt # plot
import os
import warnings

#import funcs
from datetime import datetime
from matplotlib.pyplot import cm

In [54]:
df_train = pd.read_csv('Downloads/train.csv', parse_dates=['Date']).set_index(keys=['Store','Dept','Date'], drop=False)
df_train

                       Store  Dept       Date  Weekly_Sales  IsHoliday
Store Dept Date
1     1    2010-02-05      1     1 2010-02-05      24924.50      False
           2010-02-12      1     1 2010-02-12      46039.49       True
           2010-02-19      1     1 2010-02-19      41595.55      False
           2010-02-26      1     1 2010-02-26      19403.54      False
           2010-03-05      1     1 2010-03-05      21827.90      False
...                      ...   ...        ...           ...        ...
45    98   2012-09-28     45    98 2012-09-28        508.37      False
           2012-10-05     45    98 2012-10-05        628.10      False
           2012-10-12     45    98 2012-10-12       1061.02      False
           2012-10-19     45    98 2012-10-19        760.01      False
           2012-10-26     45    98 2012-10-26       1076.80      False

[421570 rows x 5 columns]

# EDA

In [56]:
# Remove duplicate rows based on all columns
df_train.drop_duplicates()

                       Store  Dept       Date  Weekly_Sales  IsHoliday
Store Dept Date
1     1    2010-02-05      1     1 2010-02-05      24924.50      False
           2010-02-12      1     1 2010-02-12      46039.49       True
           2010-02-19      1     1 2010-02-19      41595.55      False
           2010-02-26      1     1 2010-02-26      19403.54      False
           2010-03-05      1     1 2010-03-05      21827.90      False
...                      ...   ...        ...           ...        ...
45    98   2012-09-28     45    98 2012-09-28        508.37      False
           2012-10-05     45    98 2012-10-05        628.10      False
           2012-10-12     45    98 2012-10-12       1061.02      False
           2012-10-19     45    98 2012-10-19        760.01      False
           2012-10-26     45    98 2012-10-26       1076.80      False

[421570 rows x 5 columns]

In [58]:
df_train.describe()

,Store,Dept,Date,Weekly_Sales
count,421570.000000,421570.000000,421570,421570.000000
mean,22.200546,44.260317,2011-06-18 08:30:31.963375104,15981.258123
min,1.000000,1.000000,2010-02-05 00:00:00,-4988.940000
25%,11.000000,18.000000,2010-10-08 00:00:00,2079.650000
50%,22.000000,37.000000,2011-06-17 00:00:00,7612.030000
75%,33.000000,74.000000,2012-02-24 00:00:00,20205.852500
max,45.000000,99.000000,2012-10-26 00:00:00,693099.360000
std,12.785297,30.492054,NaN,22711.183519

In [60]:
df_train.dtypes

Store                    int64
Dept                     int64
Date            datetime64[ns]
Weekly_Sales           float64
IsHoliday                 bool
dtype: object

In [66]:
# Convert 'Date' to datetime
df_train['Date'] = pd.to_datetime(df_train['Date'])

# Ensure 'Store' and 'Dept' are integers
df_train['Store'] = df_train['Store'].astype(int)
df_train['Dept'] = df_train['Dept'].astype(int)

# Ensure 'Weekly_Sales' is float
df_train['Weekly_Sales'] = df_train['Weekly_Sales'].astype(float)

# Convert 'IsHoliday' to boolean
df_train['IsHoliday'] = df_train['IsHoliday'].map({'TRUE': True, 'FALSE': False}).astype(bool)

# Verify data types after conversion
print("\nData Types After Conversion:")
print(df_train.dtypes)

Data Types After Conversion:
Store                    int64
Dept                     int64
Date            datetime64[ns]
Weekly_Sales           float64
IsHoliday                 bool
dtype: object

In [46]:
# Handle missing data 
df_train.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [48]:
df_train.fillna(method='ffill')

                       Store  Dept       Date  Weekly_Sales  IsHoliday
Store Dept Date
1     1    2010-02-05      1     1 2010-02-05      24924.50      False
           2010-02-12      1     1 2010-02-12      46039.49       True
           2010-02-19      1     1 2010-02-19      41595.55      False
           2010-02-26      1     1 2010-02-26      19403.54      False
           2010-03-05      1     1 2010-03-05      21827.90      False
...                      ...   ...        ...           ...        ...
45    98   2012-09-28     45    98 2012-09-28        508.37      False
           2012-10-05     45    98 2012-10-05        628.10      False
           2012-10-12     45    98 2012-10-12       1061.02      False
           2012-10-19     45    98 2012-10-19        760.01      False
           2012-10-26     45    98 2012-10-26       1076.80      False

[421570 rows x 5 columns]